name: Dependencies

on:
  schedule:
    # Run weekly on Mondays at 10:00 UTC
    - cron: '0 10 * * 1'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Audit dependencies
      run: cargo audit

  check-dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Check dependency tree
      run: cargo tree --duplicates
    
    - name: Check for unused dependencies
      run: |
        # Simple check for unused dependencies
        cargo build --verbose 2>&1 | grep -i "warning.*unused" || echo "No unused dependencies found"